name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install request
          npm install express
          npm install xml-js
          npm install fs-extra
          pip install requests

      - name: Run proxy server
        run: node proxy.js &
      
      - name: Run PHP proxy
        run: php -S 127.0.0.1:8000 proxy.php &

      - name: Run Python server
        run: python server.py &

      - name: Wait for servers to start
        run: sleep 10

      - name: Generate EPG
        run: python main.py

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update EPG"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
